---
{{- if .Values.create_config_configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: freqtrade-config-{{ .Release.Namespace }}
  labels:
    app: freqtrade-config
data:
  config-{{ .Release.Namespace }}.json: |
{{ toPrettyJson .Values.config | indent 4 }}
{{- end }}
