---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freqtrade-sqlite
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bot.pvc_size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freqtrade-extra-strategies
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bot.pvc_size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freqtrade-user-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bot.pvc_size }}
---   
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: freqtrade-backtesting-data
#spec:   
#  accessModes:
#  - ReadWriteOnce
#  resources: 
#    requests:
#      storage: {{ .Values.backtesting.pvc_size }}
#---     
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: freqtrade-backtesting-results
#spec:     
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests: 
#      storage: {{ .Values.backtesting.results.pvc_size }}
